/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 scene.gltf --transform 
Files: scene.gltf [4.51KB] > C:\Users\ochirkh2\Documents\Projects\Portfolio\public\3d\fantasy_sky_background\scene-transformed.glb [22.3KB] (-394%)
Author: Hannes Delbeke (https://sketchfab.com/han)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/fantasy-sky-background-15c79bb2fc1147128039fe4ff90fd5a0
Title: Fantasy Sky Background
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object001_Material__25__background_JPG_002_0.geometry} material={materials.Material__25__background_JPG_002} scale={1.548} />
    </group>
  )
}

useGLTF.preload('/scene-transformed.glb')
