'use client'
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Marco Fascinetto (https://sketchfab.com/Marco.Fascinetto)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mew-flying-5c3814b08f48493396f298d48629d4dc
Title: Mew - Flying
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Bomberman({ isRotating, ...props }) {
  const group = useRef()
  const { scene, nodes, materials, animations } = useGLTF('/3d/bomberman_flying_bot.glb')
  const { actions } = useAnimations(animations, group)
  useEffect(() => {
    if (isRotating) {
      console.log('bomberman')
      console.log(Object.keys(actions))
      actions['Armature|run'].play();
    } else {
      actions['Armature|run'].stop();
    }
  }, [actions, isRotating])
  return (
    <mesh
      ref={group}
      {...props}
      position={[0, 0, 0.3]}
      scale={[0.001, 0.001, 0.001]}
      rotation={[Math.PI / 6, Math.PI / 2, 0]}
      dispose={null}
    >
      {/* <skinnedMesh
        position={[0, 0, 0]} scale={[0.00003, 0.00003, 0.00003]}
        name="Object_7"
        geometry={nodes.Object_7.geometry}
        material={materials.blinn1}
        skeleton={nodes.Object_7.skeleton}
      /> */}
      <primitive object={scene} />
    </mesh >
  )
}