/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from 'react'
import { useThree } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { useSpring, a } from '@react-spring/three'
import { useDrag, useGesture } from '@use-gesture/react';

export function FloatingIsland2({ isRotating, setIsRotating, ...props }) {
  const { nodes, materials } = useGLTF('/3d/where_ink_pours_out_endless_night.glb')
  const islandRef = useRef();
  const { gl, viewport, size } = useThree();
  const aspect = size.width / viewport.width;

  const [springs, api] = useSpring(() => ({
    x: 0,
    config: { friction: 100 }
  }))

  const bind = useDrag(({ dragging, active, down, offset: [dx], elapsedTime }) => {
    if (down && dragging) {
      api.start({ x: dx / aspect })
    } else if (down) {
      api.stop();
    }
  })
  const rotation = springs.x.to([0, 1], [0, Math.PI]);
  return (
    
  )
}
