/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from 'react'
import { useThree, useFrame } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { useSpring, a } from '@react-spring/three'
import { useDrag, useGesture } from '@use-gesture/react';

export function JapanesePond({ isRotating, setIsRotating, ...props }) {
  const { nodes, materials } = useGLTF('/3d/japanese_pond_diorama.glb')
  const islandRef = useRef();
  const { gl, viewport, size } = useThree();
  const aspect = size.width / viewport.width;

  const [springs, api] = useSpring(() => ({
    x: 0,
    config: { friction: 100 }
  }))

  const bind = useDrag(({
    dragging,
    active,
    down,
    offset: [dx],
    elapsedTime
  }) => {
    if (down && dragging) {
      api.start({ x: dx / aspect })
    } else if (down) {
      console.log('stopping the island')
      api.stop();
    }
  })
  useFrame(({ clock }) => {
    if (isRotating) {
      islandRef.current.rotation.y -= 0.001
    }
  })
  const rotation = springs.x.to([0, 1], [0, Math.PI]);
  return (
    <a.group
      ref={islandRef}
      {...props}
      {...bind()}
      {...springs}
      rotation-y={rotation}
    >
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="33e6502e263e49b190f3594d51516be7fbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group
                  name="TreepCylinder1"
                  position={[-11.527, 17.076, 16.844]}
                  rotation={[3.052, -0.679, 3.046]}
                  scale={[4.666, 7.299, 4.94]}>
                  <mesh
                    name="TreepCylinder1_StingrayPBS4_0"
                    geometry={nodes.TreepCylinder1_StingrayPBS4_0.geometry}
                    material={materials.StingrayPBS4}
                  />
                  <group
                    name="TreepCube3"
                    position={[0.832, 4.266, 0.004]}
                    rotation={[3.136, 0.007, 3.124]}
                    scale={[0.429, 0.429, 0.803]}>
                    <mesh
                      name="TreepCube3_StingrayPBS4_0"
                      geometry={nodes.TreepCube3_StingrayPBS4_0.geometry}
                      material={materials.StingrayPBS4}
                    />
                  </group>
                  <group
                    name="pCube3"
                    position={[5.763, 2.527, -0.044]}
                    rotation={[3.136, 0.007, 3.124]}
                    scale={[1.054, 0.588, 0.931]}>
                    <mesh
                      name="pCube3_StingrayPBS4_0"
                      geometry={nodes.pCube3_StingrayPBS4_0.geometry}
                      material={materials.StingrayPBS4}
                    />
                    <group
                      name="pCube18"
                      position={[4.034, 2.37, -0.157]}
                      rotation={[-1.786, 0.925, 0.16]}
                      scale={[0.412, 0.388, 0.489]}>
                      <mesh
                        name="pCube18_StingrayPBS4_0"
                        geometry={nodes.pCube18_StingrayPBS4_0.geometry}
                        material={materials.StingrayPBS4}
                      />
                    </group>
                    <group
                      name="pCube17"
                      position={[2.828, 0.193, 1.643]}
                      rotation={[0.01, 0.608, -0.008]}
                      scale={[0.39, 0.416, 0.481]}>
                      <mesh
                        name="pCube17_StingrayPBS4_0"
                        geometry={nodes.pCube17_StingrayPBS4_0.geometry}
                        material={materials.StingrayPBS4}
                      />
                    </group>
                  </group>
                  <group
                    name="pCube19"
                    position={[-7.906, 4.07, -2.308]}
                    rotation={[0.081, -0.405, -0.084]}
                    scale={[0.812, 0.453, 0.717]}>
                    <mesh
                      name="pCube19_StingrayPBS4_0"
                      geometry={nodes.pCube19_StingrayPBS4_0.geometry}
                      material={materials.StingrayPBS4}
                    />
                    <group
                      name="pCube18_1"
                      position={[4.034, 2.37, -0.157]}
                      rotation={[-1.786, 0.925, 0.16]}
                      scale={[0.412, 0.388, 0.489]}>
                      <mesh
                        name="pCube18_StingrayPBS4_0_1"
                        geometry={nodes.pCube18_StingrayPBS4_0_1.geometry}
                        material={materials.StingrayPBS4}
                      />
                    </group>
                    <group
                      name="pCube17_1"
                      position={[2.828, 0.193, 1.643]}
                      rotation={[0.01, 0.608, -0.008]}
                      scale={[0.39, 0.416, 0.481]}>
                      <mesh
                        name="pCube17_StingrayPBS4_0_1"
                        geometry={nodes.pCube17_StingrayPBS4_0_1.geometry}
                        material={materials.StingrayPBS4}
                      />
                    </group>
                  </group>
                  <group
                    name="pCube20"
                    position={[-2.561, 1.84, -4.975]}
                    rotation={[1.134, -1.255, 1.244]}
                    scale={[0.671, 0.588, 0.931]}>
                    <mesh
                      name="pCube20_StingrayPBS4_0"
                      geometry={nodes.pCube20_StingrayPBS4_0.geometry}
                      material={materials.StingrayPBS4}
                    />
                    <group
                      name="pCube18_2"
                      position={[4.034, 2.37, -0.157]}
                      rotation={[-1.786, 0.925, 0.16]}
                      scale={[0.412, 0.388, 0.489]}>
                      <mesh
                        name="pCube18_StingrayPBS4_0_2"
                        geometry={nodes.pCube18_StingrayPBS4_0_2.geometry}
                        material={materials.StingrayPBS4}
                      />
                    </group>
                    <group
                      name="pCube17_2"
                      position={[2.828, 0.193, 1.643]}
                      rotation={[0.01, 0.608, -0.008]}
                      scale={[0.39, 0.416, 0.481]}>
                      <mesh
                        name="pCube17_StingrayPBS4_0_2"
                        geometry={nodes.pCube17_StingrayPBS4_0_2.geometry}
                        material={materials.StingrayPBS4}
                      />
                    </group>
                  </group>
                  <group
                    name="pCube21"
                    position={[-2.798, 2.945, 3.311]}
                    rotation={[-0.11, 1.403, 0.106]}
                    scale={[0.429, 0.429, 0.803]}>
                    <mesh
                      name="pCube21_StingrayPBS4_0"
                      geometry={nodes.pCube21_StingrayPBS4_0.geometry}
                      material={materials.StingrayPBS4}
                    />
                  </group>
                  <group
                    name="pCube22"
                    position={[-6.862, 2.017, 6.211]}
                    rotation={[-0.027, 0.895, 0.028]}
                    scale={[1.054, 0.588, 0.931]}>
                    <mesh
                      name="pCube22_StingrayPBS4_0"
                      geometry={nodes.pCube22_StingrayPBS4_0.geometry}
                      material={materials.StingrayPBS4}
                    />
                    <group
                      name="pCube18_3"
                      position={[4.034, 2.37, -0.157]}
                      rotation={[-1.786, 0.925, 0.16]}
                      scale={[0.412, 0.388, 0.489]}>
                      <mesh
                        name="pCube18_StingrayPBS4_0_3"
                        geometry={nodes.pCube18_StingrayPBS4_0_3.geometry}
                        material={materials.StingrayPBS4}
                      />
                    </group>
                    <group
                      name="pCube17_3"
                      position={[2.828, 0.193, 1.643]}
                      rotation={[0.01, 0.608, -0.008]}
                      scale={[0.39, 0.416, 0.481]}>
                      <mesh
                        name="pCube17_StingrayPBS4_0_3"
                        geometry={nodes.pCube17_StingrayPBS4_0_3.geometry}
                        material={materials.StingrayPBS4}
                      />
                    </group>
                  </group>
                  <group
                    name="pCube23"
                    position={[-1.268, 5.881, -0.02]}
                    rotation={[3.136, 0.007, 2.66]}
                    scale={[0.187, 0.187, 0.351]}>
                    <mesh
                      name="pCube23_StingrayPBS4_0"
                      geometry={nodes.pCube23_StingrayPBS4_0.geometry}
                      material={materials.StingrayPBS4}
                    />
                  </group>
                </group>
                <group
                  name="pPlane1"
                  position={[12.371, -1.468, 0]}
                  scale={[214.539, 215.135, 214.539]}>
                  <mesh
                    name="pPlane1_lambert2_0"
                    geometry={nodes.pPlane1_lambert2_0.geometry}
                    material={materials.lambert2}
                  />
                  <group name="pPlane2" position={[0.259, 0.002, 0]} scale={0.042}>
                    <mesh
                      name="pPlane2_lambert3_0"
                      geometry={nodes.pPlane2_lambert3_0.geometry}
                      material={materials.lambert3}
                    />
                  </group>
                  <group name="pPlane3" position={[-0.233, 0, 0]} scale={0.042}>
                    <mesh
                      name="pPlane3_lambert3_0"
                      geometry={nodes.pPlane3_lambert3_0.geometry}
                      material={materials.lambert3}
                    />
                  </group>
                  <group
                    name="pPlane4"
                    position={[-0.234, 0.001, 0.164]}
                    rotation={[-0.055, 1.043, 0.031]}
                    scale={0.042}>
                    <mesh
                      name="pPlane4_lambert3_0"
                      geometry={nodes.pPlane4_lambert3_0.geometry}
                      material={materials.lambert3}
                    />
                  </group>
                  <group
                    name="pPlane5"
                    position={[-0.193, 0.003, 0.184]}
                    rotation={[-3.119, 0.62, 3.071]}
                    scale={0.042}>
                    <mesh
                      name="pPlane5_lambert3_0"
                      geometry={nodes.pPlane5_lambert3_0.geometry}
                      material={materials.lambert3}
                    />
                  </group>
                  <group name="pPlane6" position={[-0.225, 0.002, 0.085]} scale={0.063}>
                    <mesh
                      name="pPlane6_lambert3_0"
                      geometry={nodes.pPlane6_lambert3_0.geometry}
                      material={materials.lambert3}
                    />
                  </group>
                  <group
                    name="pPlane18"
                    position={[-0.215, 0.002, 0.039]}
                    rotation={[0, 0.715, 0]}
                    scale={0.063}>
                    <mesh
                      name="pPlane18_lambert3_0"
                      geometry={nodes.pPlane18_lambert3_0.geometry}
                      material={materials.lambert3}
                    />
                  </group>
                </group>
                <group
                  name="Island_1"
                  position={[9.529, 0, 17.586]}
                  rotation={[0, 1.156, 0]}
                  scale={[29.513, 8.578, 49.35]}>
                  <mesh
                    name="Island_1_StingrayPBS2_0"
                    geometry={nodes.Island_1_StingrayPBS2_0.geometry}
                    material={materials.StingrayPBS2}
                  />
                </group>
                <group name="BridgeBridge">
                  <mesh
                    name="BridgeBridge_BridgeStingrayPBS2_0"
                    geometry={nodes.BridgeBridge_BridgeStingrayPBS2_0.geometry}
                    material={materials.BridgeStingrayPBS2}
                  />
                  <group name="BridgePole1">
                    <mesh
                      name="BridgePole1_BridgeStingrayPBS1_0"
                      geometry={nodes.BridgePole1_BridgeStingrayPBS1_0.geometry}
                      material={materials.BridgeStingrayPBS1}
                    />
                    <group name="BridgepSphere1">
                      <mesh
                        name="BridgepSphere1_BridgeStingrayPBS1_0"
                        geometry={nodes.BridgepSphere1_BridgeStingrayPBS1_0.geometry}
                        material={materials.BridgeStingrayPBS1}
                      />
                    </group>
                  </group>
                  <group name="BridgePole4">
                    <mesh
                      name="BridgePole4_BridgeStingrayPBS1_0"
                      geometry={nodes.BridgePole4_BridgeStingrayPBS1_0.geometry}
                      material={materials.BridgeStingrayPBS1}
                    />
                    <group name="BridgepSphere1_1">
                      <mesh
                        name="BridgepSphere1_BridgeStingrayPBS1_0_1"
                        geometry={nodes.BridgepSphere1_BridgeStingrayPBS1_0_1.geometry}
                        material={materials.BridgeStingrayPBS1}
                      />
                    </group>
                  </group>
                  <group name="BridgePole5">
                    <mesh
                      name="BridgePole5_BridgeStingrayPBS1_0"
                      geometry={nodes.BridgePole5_BridgeStingrayPBS1_0.geometry}
                      material={materials.BridgeStingrayPBS1}
                    />
                    <group name="BridgepSphere1_2">
                      <mesh
                        name="BridgepSphere1_BridgeStingrayPBS1_0_2"
                        geometry={nodes.BridgepSphere1_BridgeStingrayPBS1_0_2.geometry}
                        material={materials.BridgeStingrayPBS1}
                      />
                    </group>
                  </group>
                  <group name="BridgePole6">
                    <mesh
                      name="BridgePole6_BridgeStingrayPBS1_0"
                      geometry={nodes.BridgePole6_BridgeStingrayPBS1_0.geometry}
                      material={materials.BridgeStingrayPBS1}
                    />
                    <group name="BridgepSphere1_3">
                      <mesh
                        name="BridgepSphere1_BridgeStingrayPBS1_0_3"
                        geometry={nodes.BridgepSphere1_BridgeStingrayPBS1_0_3.geometry}
                        material={materials.BridgeStingrayPBS1}
                      />
                    </group>
                  </group>
                  <group name="BridgeBottom2">
                    <mesh
                      name="BridgeBottom2_BridgeStingrayPBS2_0"
                      geometry={nodes.BridgeBottom2_BridgeStingrayPBS2_0.geometry}
                      material={materials.BridgeStingrayPBS2}
                    />
                  </group>
                  <group name="BridgeBottom3">
                    <mesh
                      name="BridgeBottom3_BridgeStingrayPBS2_0"
                      geometry={nodes.BridgeBottom3_BridgeStingrayPBS2_0.geometry}
                      material={materials.BridgeStingrayPBS2}
                    />
                  </group>
                  <group name="BridgepCube20">
                    <mesh
                      name="BridgepCube20_BridgeStingrayPBS1_0"
                      geometry={nodes.BridgepCube20_BridgeStingrayPBS1_0.geometry}
                      material={materials.BridgeStingrayPBS1}
                    />
                  </group>
                  <group name="BridgepCube19">
                    <mesh
                      name="BridgepCube19_BridgeStingrayPBS1_0"
                      geometry={nodes.BridgepCube19_BridgeStingrayPBS1_0.geometry}
                      material={materials.BridgeStingrayPBS1}
                    />
                  </group>
                  <group name="BridgepCube18">
                    <mesh
                      name="BridgepCube18_BridgeStingrayPBS1_0"
                      geometry={nodes.BridgepCube18_BridgeStingrayPBS1_0.geometry}
                      material={materials.BridgeStingrayPBS1}
                    />
                  </group>
                  <group name="BridgepCube17">
                    <mesh
                      name="BridgepCube17_BridgeStingrayPBS1_0"
                      geometry={nodes.BridgepCube17_BridgeStingrayPBS1_0.geometry}
                      material={materials.BridgeStingrayPBS1}
                    />
                  </group>
                  <group name="BridgepCube16">
                    <mesh
                      name="BridgepCube16_BridgeStingrayPBS1_0"
                      geometry={nodes.BridgepCube16_BridgeStingrayPBS1_0.geometry}
                      material={materials.BridgeStingrayPBS1}
                    />
                  </group>
                  <group name="BridgepCube15">
                    <mesh
                      name="BridgepCube15_BridgeStingrayPBS1_0"
                      geometry={nodes.BridgepCube15_BridgeStingrayPBS1_0.geometry}
                      material={materials.BridgeStingrayPBS1}
                    />
                  </group>
                  <group name="BridgepCube14">
                    <mesh
                      name="BridgepCube14_BridgeStingrayPBS1_0"
                      geometry={nodes.BridgepCube14_BridgeStingrayPBS1_0.geometry}
                      material={materials.BridgeStingrayPBS1}
                    />
                  </group>
                  <group name="BridgepCube13">
                    <mesh
                      name="BridgepCube13_BridgeStingrayPBS1_0"
                      geometry={nodes.BridgepCube13_BridgeStingrayPBS1_0.geometry}
                      material={materials.BridgeStingrayPBS1}
                    />
                  </group>
                  <group name="BridgepCube12">
                    <mesh
                      name="BridgepCube12_BridgeStingrayPBS1_0"
                      geometry={nodes.BridgepCube12_BridgeStingrayPBS1_0.geometry}
                      material={materials.BridgeStingrayPBS1}
                    />
                  </group>
                  <group name="BridgepCube11">
                    <mesh
                      name="BridgepCube11_BridgeStingrayPBS1_0"
                      geometry={nodes.BridgepCube11_BridgeStingrayPBS1_0.geometry}
                      material={materials.BridgeStingrayPBS1}
                    />
                  </group>
                  <group name="BridgepCube10">
                    <mesh
                      name="BridgepCube10_BridgeStingrayPBS1_0"
                      geometry={nodes.BridgepCube10_BridgeStingrayPBS1_0.geometry}
                      material={materials.BridgeStingrayPBS1}
                    />
                  </group>
                  <group name="BridgepCube9">
                    <mesh
                      name="BridgepCube9_BridgeStingrayPBS1_0"
                      geometry={nodes.BridgepCube9_BridgeStingrayPBS1_0.geometry}
                      material={materials.BridgeStingrayPBS1}
                    />
                  </group>
                  <group name="BridgepCube8">
                    <mesh
                      name="BridgepCube8_BridgeStingrayPBS1_0"
                      geometry={nodes.BridgepCube8_BridgeStingrayPBS1_0.geometry}
                      material={materials.BridgeStingrayPBS1}
                    />
                  </group>
                  <group name="BridgeTop1">
                    <mesh
                      name="BridgeTop1_BridgeStingrayPBS1_0"
                      geometry={nodes.BridgeTop1_BridgeStingrayPBS1_0.geometry}
                      material={materials.BridgeStingrayPBS1}
                    />
                  </group>
                  <group name="BridgepCube2">
                    <mesh
                      name="BridgepCube2_BridgeStingrayPBS1_0"
                      geometry={nodes.BridgepCube2_BridgeStingrayPBS1_0.geometry}
                      material={materials.BridgeStingrayPBS1}
                    />
                  </group>
                  <group name="BridgeTop">
                    <mesh
                      name="BridgeTop_BridgeStingrayPBS1_0"
                      geometry={nodes.BridgeTop_BridgeStingrayPBS1_0.geometry}
                      material={materials.BridgeStingrayPBS1}
                    />
                  </group>
                  <group name="BridgeBottom4">
                    <mesh
                      name="BridgeBottom4_BridgeStingrayPBS2_0"
                      geometry={nodes.BridgeBottom4_BridgeStingrayPBS2_0.geometry}
                      material={materials.BridgeStingrayPBS2}
                    />
                  </group>
                  <group name="BridgeBottom5">
                    <mesh
                      name="BridgeBottom5_BridgeStingrayPBS2_0"
                      geometry={nodes.BridgeBottom5_BridgeStingrayPBS2_0.geometry}
                      material={materials.BridgeStingrayPBS2}
                    />
                  </group>
                  <group name="BridgepPlane1">
                    <mesh
                      name="BridgepPlane1_Bridgelambert2_0"
                      geometry={nodes.BridgepPlane1_Bridgelambert2_0.geometry}
                      material={materials.Bridgelambert2}
                    />
                    <group name="BridgepPlane2">
                      <mesh
                        name="BridgepPlane2_Bridgelambert2_0"
                        geometry={nodes.BridgepPlane2_Bridgelambert2_0.geometry}
                        material={materials.Bridgelambert2}
                      />
                    </group>
                    <group name="BridgepPlane3">
                      <mesh
                        name="BridgepPlane3_Bridgelambert2_0"
                        geometry={nodes.BridgepPlane3_Bridgelambert2_0.geometry}
                        material={materials.Bridgelambert2}
                      />
                    </group>
                    <group name="BridgepPlane4">
                      <mesh
                        name="BridgepPlane4_Bridgelambert2_0"
                        geometry={nodes.BridgepPlane4_Bridgelambert2_0.geometry}
                        material={materials.Bridgelambert2}
                      />
                    </group>
                  </group>
                </group>
                <group
                  name="pPlane7"
                  position={[12.449, -3.929, 0]}
                  scale={[483.865, 485.21, 483.865]}>
                  <mesh
                    name="pPlane7_lambert4_0"
                    geometry={nodes.pPlane7_lambert4_0.geometry}
                    material={materials.lambert4}
                  />
                </group>
                <group
                  name="Rock"
                  position={[-10.445, -3.524, -10.807]}
                  rotation={[-2.759, 0.669, 2.535]}
                  scale={2.284}>
                  <mesh
                    name="Rock_RocksStingrayPBS1_0"
                    geometry={nodes.Rock_RocksStingrayPBS1_0.geometry}
                    material={materials.RocksStingrayPBS1}
                  />
                  <group
                    name="RockspCube1"
                    position={[-0.754, -0.482, 0.725]}
                    rotation={[3.112, -0.756, 2.657]}>
                    <mesh
                      name="RockspCube1_RocksStingrayPBS1_0"
                      geometry={nodes.RockspCube1_RocksStingrayPBS1_0.geometry}
                      material={materials.RocksStingrayPBS1}
                    />
                  </group>
                  <group
                    name="pCube4"
                    position={[-2.162, -2.818, 3.932]}
                    rotation={[3.112, -0.756, 2.657]}>
                    <mesh
                      name="pCube4_RocksStingrayPBS1_0"
                      geometry={nodes.pCube4_RocksStingrayPBS1_0.geometry}
                      material={materials.RocksStingrayPBS1}
                    />
                  </group>
                  <group
                    name="pCube1"
                    position={[-1.926, -1.266, 1.978]}
                    rotation={[-2.639, 0.052, 3.063]}
                    scale={1.57}>
                    <mesh
                      name="pCube1_RocksStingrayPBS1_0"
                      geometry={nodes.pCube1_RocksStingrayPBS1_0.geometry}
                      material={materials.RocksStingrayPBS1}
                    />
                  </group>
                  <group
                    name="pCube5"
                    position={[-3.402, -2.132, 3.175]}
                    rotation={[-2.989, -0.383, 2.767]}>
                    <mesh
                      name="pCube5_RocksStingrayPBS1_0"
                      geometry={nodes.pCube5_RocksStingrayPBS1_0.geometry}
                      material={materials.RocksStingrayPBS1}
                    />
                  </group>
                  <group
                    name="pCube6"
                    position={[-2.65, 1.483, -7.463]}
                    rotation={[-2.639, 0.052, 3.063]}
                    scale={1.57}>
                    <mesh
                      name="pCube6_RocksStingrayPBS1_0"
                      geometry={nodes.pCube6_RocksStingrayPBS1_0.geometry}
                      material={materials.RocksStingrayPBS1}
                    />
                  </group>
                  <group
                    name="pCube7"
                    position={[-2.518, 1.229, -10.237]}
                    rotation={[2.925, -1.314, 2.806]}
                    scale={2.37}>
                    <mesh
                      name="pCube7_RocksStingrayPBS1_0"
                      geometry={nodes.pCube7_RocksStingrayPBS1_0.geometry}
                      material={materials.RocksStingrayPBS1}
                    />
                  </group>
                  <group
                    name="pCube8"
                    position={[9.716, -1.055, 9.373]}
                    rotation={[-2.983, -0.975, 3.089]}
                    scale={2.37}>
                    <mesh
                      name="pCube8_RocksStingrayPBS1_0"
                      geometry={nodes.pCube8_RocksStingrayPBS1_0.geometry}
                      material={materials.RocksStingrayPBS1}
                    />
                  </group>
                  <group
                    name="pCube9"
                    position={[10.249, -0.408, 11.6]}
                    rotation={[-2.639, 0.052, 3.063]}
                    scale={1.57}>
                    <mesh
                      name="pCube9_RocksStingrayPBS1_0"
                      geometry={nodes.pCube9_RocksStingrayPBS1_0.geometry}
                      material={materials.RocksStingrayPBS1}
                    />
                  </group>
                  <group
                    name="pCube10"
                    position={[-13.448, -7.242, 6.989]}
                    rotation={[3.112, -0.756, 2.657]}>
                    <mesh
                      name="pCube10_RocksStingrayPBS1_0"
                      geometry={nodes.pCube10_RocksStingrayPBS1_0.geometry}
                      material={materials.RocksStingrayPBS1}
                    />
                  </group>
                  <group
                    name="pCube11"
                    position={[-17.853, -9.836, 7.162]}
                    rotation={[-2.737, -0.328, 2.529]}
                    scale={1.918}>
                    <mesh
                      name="pCube11_RocksStingrayPBS1_0"
                      geometry={nodes.pCube11_RocksStingrayPBS1_0.geometry}
                      material={materials.RocksStingrayPBS1}
                    />
                  </group>
                  <group
                    name="pCube12"
                    position={[-15.35, -8.903, 6.829]}
                    rotation={[0.664, -1.262, 0.078]}
                    scale={2.175}>
                    <mesh
                      name="pCube12_RocksStingrayPBS1_0"
                      geometry={nodes.pCube12_RocksStingrayPBS1_0.geometry}
                      material={materials.RocksStingrayPBS1}
                    />
                  </group>
                  <group
                    name="pCube13"
                    position={[-5.329, 1.15, -12.918]}
                    rotation={[-2.62, -1.25, -2.381]}
                    scale={3.845}>
                    <mesh
                      name="pCube13_RocksStingrayPBS1_0"
                      geometry={nodes.pCube13_RocksStingrayPBS1_0.geometry}
                      material={materials.RocksStingrayPBS1}
                    />
                  </group>
                  <group
                    name="pCube14"
                    position={[-7.508, 0.98, -14.656]}
                    rotation={[2.473, -0.977, 2.944]}
                    scale={2.37}>
                    <mesh
                      name="pCube14_RocksStingrayPBS1_0"
                      geometry={nodes.pCube14_RocksStingrayPBS1_0.geometry}
                      material={materials.RocksStingrayPBS1}
                    />
                  </group>
                  <group
                    name="pCube15"
                    position={[-29.188, -9.452, -5.876]}
                    rotation={[-2.737, -0.328, 2.529]}
                    scale={1.386}>
                    <mesh
                      name="pCube15_RocksStingrayPBS1_0"
                      geometry={nodes.pCube15_RocksStingrayPBS1_0.geometry}
                      material={materials.RocksStingrayPBS1}
                    />
                  </group>
                  <group
                    name="pCube16"
                    position={[-7.249, -10.661, 23]}
                    rotation={[3.097, -1.258, 2.366]}
                    scale={1.608}>
                    <mesh
                      name="pCube16_RocksStingrayPBS1_0"
                      geometry={nodes.pCube16_RocksStingrayPBS1_0.geometry}
                      material={materials.RocksStingrayPBS1}
                    />
                  </group>
                  <group
                    name="pCube25"
                    position={[-3.435, -12.274, 27.382]}
                    rotation={[-2.62, -1.25, -2.381]}
                    scale={3.335}>
                    <mesh
                      name="pCube25_RocksStingrayPBS1_0"
                      geometry={nodes.pCube25_RocksStingrayPBS1_0.geometry}
                      material={materials.RocksStingrayPBS1}
                    />
                  </group>
                  <group
                    name="pCube26"
                    position={[-5.726, -11.434, 27.124]}
                    rotation={[3.097, -1.258, 2.366]}
                    scale={1.608}>
                    <mesh
                      name="pCube26_RocksStingrayPBS1_0"
                      geometry={nodes.pCube26_RocksStingrayPBS1_0.geometry}
                      material={materials.RocksStingrayPBS1}
                    />
                  </group>
                  <group
                    name="pCube27"
                    position={[-4.797, -11.405, 28.109]}
                    rotation={[0.767, -0.815, -0.165]}
                    scale={1.608}>
                    <mesh
                      name="pCube27_RocksStingrayPBS1_0"
                      geometry={nodes.pCube27_RocksStingrayPBS1_0.geometry}
                      material={materials.RocksStingrayPBS1}
                    />
                  </group>
                  <group
                    name="pCube28"
                    position={[-2.3, -12.421, 29.967]}
                    rotation={[0.754, -0.102, 0.369]}
                    scale={2.093}>
                    <mesh
                      name="pCube28_RocksStingrayPBS1_0"
                      geometry={nodes.pCube28_RocksStingrayPBS1_0.geometry}
                      material={materials.RocksStingrayPBS1}
                    />
                  </group>
                  <group
                    name="pCube30"
                    position={[-17.363, -3.539, -12.259]}
                    rotation={[2.473, -0.977, 2.944]}
                    scale={2.37}>
                    <mesh
                      name="pCube30_RocksStingrayPBS1_0"
                      geometry={nodes.pCube30_RocksStingrayPBS1_0.geometry}
                      material={materials.RocksStingrayPBS1}
                    />
                  </group>
                  <group
                    name="pCube31"
                    position={[-19.012, -4.925, -12.417]}
                    rotation={[2.75, 0.795, 2.353]}
                    scale={2.37}>
                    <mesh
                      name="pCube31_RocksStingrayPBS1_0"
                      geometry={nodes.pCube31_RocksStingrayPBS1_0.geometry}
                      material={materials.RocksStingrayPBS1}
                    />
                  </group>
                  <group
                    name="pCube32"
                    position={[7.731, -4.968, 21.168]}
                    rotation={[-2.639, 0.052, 3.063]}
                    scale={1.57}>
                    <mesh
                      name="pCube32_RocksStingrayPBS1_0"
                      geometry={nodes.pCube32_RocksStingrayPBS1_0.geometry}
                      material={materials.RocksStingrayPBS1}
                    />
                  </group>
                </group>
                <group name="Moon" position={[71.739, 82, 34.748]}>
                  <group name="Object_167" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_168" />
                  </group>
                </group>
                <group
                  name="KoiKoi"
                  position={[44.739, -3.489, -21.789]}
                  rotation={[0.517, 0.016, -0.004]}
                  scale={0.46}>
                  <mesh
                    name="KoiKoi_KoiStingrayPBS1_0"
                    geometry={nodes.KoiKoi_KoiStingrayPBS1_0.geometry}
                    material={materials.KoiStingrayPBS1}
                  />
                  <group
                    name="KoipCube2"
                    position={[0, 0.848, 2.21]}
                    rotation={[2.991, 0, 0]}
                    scale={[0.154, 1, 1]}>
                    <mesh
                      name="KoipCube2_KoiStingrayPBS1_0"
                      geometry={nodes.KoipCube2_KoiStingrayPBS1_0.geometry}
                      material={materials.KoiStingrayPBS1}
                    />
                  </group>
                  <group name="KoipCube1" position={[0, 3.649, 0]} scale={[0.154, 1, 1]}>
                    <mesh
                      name="KoipCube1_KoiStingrayPBS1_0"
                      geometry={nodes.KoipCube1_KoiStingrayPBS1_0.geometry}
                      material={materials.KoiStingrayPBS1}
                    />
                  </group>
                  <group
                    name="KoiFin1"
                    position={[1.276, 1.338, -2.335]}
                    rotation={[0, 0.699, 0]}
                    scale={[0.109, 0.817, 0.817]}>
                    <mesh
                      name="KoiFin1_KoiStingrayPBS1_0"
                      geometry={nodes.KoiFin1_KoiStingrayPBS1_0.geometry}
                      material={materials.KoiStingrayPBS1}
                    />
                  </group>
                  <group
                    name="KoiFin"
                    position={[-1.421, 1.33, -2.335]}
                    rotation={[0, -0.676, 0]}
                    scale={[0.109, 0.817, 0.817]}>
                    <mesh
                      name="KoiFin_KoiStingrayPBS1_0"
                      geometry={nodes.KoiFin_KoiStingrayPBS1_0.geometry}
                      material={materials.KoiStingrayPBS1}
                    />
                  </group>
                </group>
                <group name="Koi1" position={[0.603, 0, -1.549]}>
                  <mesh
                    name="Koi1_KoiStingrayPBS1_0"
                    geometry={nodes.Koi1_KoiStingrayPBS1_0.geometry}
                    material={materials.KoiStingrayPBS1}
                  />
                  <group name="pCube2">
                    <mesh
                      name="pCube2_KoiStingrayPBS1_0"
                      geometry={nodes.pCube2_KoiStingrayPBS1_0.geometry}
                      material={materials.KoiStingrayPBS1}
                    />
                  </group>
                  <group name="pCube1_1">
                    <mesh
                      name="pCube1_KoiStingrayPBS1_0"
                      geometry={nodes.pCube1_KoiStingrayPBS1_0.geometry}
                      material={materials.KoiStingrayPBS1}
                    />
                  </group>
                  <group name="Fin1">
                    <mesh
                      name="Fin1_KoiStingrayPBS1_0"
                      geometry={nodes.Fin1_KoiStingrayPBS1_0.geometry}
                      material={materials.KoiStingrayPBS1}
                    />
                  </group>
                  <group name="Fin">
                    <mesh
                      name="Fin_KoiStingrayPBS1_0"
                      geometry={nodes.Fin_KoiStingrayPBS1_0.geometry}
                      material={materials.KoiStingrayPBS1}
                    />
                  </group>
                </group>
                <group name="Koi2" position={[-47.424, -0.445, 3.752]}>
                  <mesh
                    name="Koi2_KoiStingrayPBS1_0"
                    geometry={nodes.Koi2_KoiStingrayPBS1_0.geometry}
                    material={materials.KoiStingrayPBS1}
                  />
                  <group name="pCube2_1">
                    <mesh
                      name="pCube2_KoiStingrayPBS1_0_1"
                      geometry={nodes.pCube2_KoiStingrayPBS1_0_1.geometry}
                      material={materials.KoiStingrayPBS1}
                    />
                  </group>
                  <group name="pCube1_2">
                    <mesh
                      name="pCube1_KoiStingrayPBS1_0_1"
                      geometry={nodes.pCube1_KoiStingrayPBS1_0_1.geometry}
                      material={materials.KoiStingrayPBS1}
                    />
                  </group>
                  <group name="Fin1_1">
                    <mesh
                      name="Fin1_KoiStingrayPBS1_0_1"
                      geometry={nodes.Fin1_KoiStingrayPBS1_0_1.geometry}
                      material={materials.KoiStingrayPBS1}
                    />
                  </group>
                  <group name="Fin_1">
                    <mesh
                      name="Fin_KoiStingrayPBS1_0_1"
                      geometry={nodes.Fin_KoiStingrayPBS1_0_1.geometry}
                      material={materials.KoiStingrayPBS1}
                    />
                  </group>
                </group>
                <group
                  name="Bench1"
                  position={[27.239, 5.749, 23.441]}
                  rotation={[-3.088, -1.114, -3.1]}
                  scale={[1.395, 1.023, 0.837]}>
                  <mesh
                    name="Bench1_BenchStingrayPBS1_0"
                    geometry={nodes.Bench1_BenchStingrayPBS1_0.geometry}
                    material={materials.BenchStingrayPBS1}
                  />
                  <group
                    name="BenchpCube19"
                    position={[-3.064, 4.947, -0.006]}
                    scale={[0.255, 1.099, 6.5]}>
                    <mesh
                      name="BenchpCube19_BenchStingrayPBS1_0"
                      geometry={nodes.BenchpCube19_BenchStingrayPBS1_0.geometry}
                      material={materials.BenchStingrayPBS1}
                    />
                  </group>
                  <group
                    name="BenchpCube18"
                    position={[2.917, 4.967, -0.006]}
                    scale={[0.255, 1.099, 6.5]}>
                    <mesh
                      name="BenchpCube18_BenchStingrayPBS1_0"
                      geometry={nodes.BenchpCube18_BenchStingrayPBS1_0.geometry}
                      material={materials.BenchStingrayPBS1}
                    />
                  </group>
                  <group
                    name="BenchpCube17"
                    position={[2.917, -0.465, -0.006]}
                    scale={[0.255, 1.099, 6.5]}>
                    <mesh
                      name="BenchpCube17_BenchStingrayPBS1_0"
                      geometry={nodes.BenchpCube17_BenchStingrayPBS1_0.geometry}
                      material={materials.BenchStingrayPBS1}
                    />
                  </group>
                  <group
                    name="BenchpCube2"
                    position={[-3.064, -0.465, -0.006]}
                    scale={[0.255, 1.099, 6.5]}>
                    <mesh
                      name="BenchpCube2_BenchStingrayPBS1_0"
                      geometry={nodes.BenchpCube2_BenchStingrayPBS1_0.geometry}
                      material={materials.BenchStingrayPBS1}
                    />
                  </group>
                  <group
                    name="Benchpost7"
                    position={[2.949, 2.029, 3.841]}
                    scale={[1, 6.101, 1.259]}>
                    <mesh
                      name="Benchpost7_BenchStingrayPBS2_0"
                      geometry={nodes.Benchpost7_BenchStingrayPBS2_0.geometry}
                      material={materials.BenchStingrayPBS2}
                    />
                    <group name="Benchpost4" position={[0, 0, -5.908]}>
                      <mesh
                        name="Benchpost4_BenchStingrayPBS2_0"
                        geometry={nodes.Benchpost4_BenchStingrayPBS2_0.geometry}
                        material={materials.BenchStingrayPBS2}
                      />
                    </group>
                    <group name="Benchpost5" position={[-5.997, 0, -5.908]}>
                      <mesh
                        name="Benchpost5_BenchStingrayPBS2_0"
                        geometry={nodes.Benchpost5_BenchStingrayPBS2_0.geometry}
                        material={materials.BenchStingrayPBS2}
                      />
                    </group>
                  </group>
                  <group
                    name="Benchpost6"
                    position={[2.949, 2.029, 3.841]}
                    scale={[1, 6.101, 1.259]}>
                    <mesh
                      name="Benchpost6_BenchStingrayPBS2_0"
                      geometry={nodes.Benchpost6_BenchStingrayPBS2_0.geometry}
                      material={materials.BenchStingrayPBS2}
                    />
                    <group name="Benchpost4_1" position={[0, 0, -5.908]}>
                      <mesh
                        name="Benchpost4_BenchStingrayPBS2_0_1"
                        geometry={nodes.Benchpost4_BenchStingrayPBS2_0_1.geometry}
                        material={materials.BenchStingrayPBS2}
                      />
                    </group>
                    <group name="Benchpost5_1" position={[-5.997, 0, -5.908]}>
                      <mesh
                        name="Benchpost5_BenchStingrayPBS2_0_1"
                        geometry={nodes.Benchpost5_BenchStingrayPBS2_0_1.geometry}
                        material={materials.BenchStingrayPBS2}
                      />
                    </group>
                  </group>
                  <group
                    name="Benchpost3"
                    position={[2.949, 2.029, 3.841]}
                    scale={[1, 6.101, 1.259]}>
                    <mesh
                      name="Benchpost3_BenchStingrayPBS2_0"
                      geometry={nodes.Benchpost3_BenchStingrayPBS2_0.geometry}
                      material={materials.BenchStingrayPBS2}
                    />
                    <group name="Benchpost4_2" position={[0, 0, -5.908]}>
                      <mesh
                        name="Benchpost4_BenchStingrayPBS2_0_2"
                        geometry={nodes.Benchpost4_BenchStingrayPBS2_0_2.geometry}
                        material={materials.BenchStingrayPBS2}
                      />
                    </group>
                    <group name="Benchpost5_2" position={[-5.997, 0, -5.908]}>
                      <mesh
                        name="Benchpost5_BenchStingrayPBS2_0_2"
                        geometry={nodes.Benchpost5_BenchStingrayPBS2_0_2.geometry}
                        material={materials.BenchStingrayPBS2}
                      />
                    </group>
                    <group name="Benchpost8" position={[-5.997, 0, -0.015]}>
                      <mesh
                        name="Benchpost8_BenchStingrayPBS2_0"
                        geometry={nodes.Benchpost8_BenchStingrayPBS2_0.geometry}
                        material={materials.BenchStingrayPBS2}
                      />
                    </group>
                  </group>
                  <group
                    name="BenchpCube4"
                    position={[0, 5.445, 3.854]}
                    rotation={[Math.PI, 0, 0]}
                    scale={[-10.411, -0.773, -0.802]}>
                    <mesh
                      name="BenchpCube4_BenchStingrayPBS1_0"
                      geometry={nodes.BenchpCube4_BenchStingrayPBS1_0.geometry}
                      material={materials.BenchStingrayPBS1}
                    />
                    <group name="BenchpCube12" position={[0, 0, -9.357]}>
                      <mesh
                        name="BenchpCube12_BenchStingrayPBS1_0"
                        geometry={nodes.BenchpCube12_BenchStingrayPBS1_0.geometry}
                        material={materials.BenchStingrayPBS1}
                      />
                    </group>
                    <group name="BenchpCube13" position={[0, 0, -7.552]}>
                      <mesh
                        name="BenchpCube13_BenchStingrayPBS1_0"
                        geometry={nodes.BenchpCube13_BenchStingrayPBS1_0.geometry}
                        material={materials.BenchStingrayPBS1}
                      />
                    </group>
                    <group name="BenchpCube14" position={[0, 0, -5.702]}>
                      <mesh
                        name="BenchpCube14_BenchStingrayPBS1_0"
                        geometry={nodes.BenchpCube14_BenchStingrayPBS1_0.geometry}
                        material={materials.BenchStingrayPBS1}
                      />
                    </group>
                    <group name="BenchpCube15" position={[0, 0, -3.74]}>
                      <mesh
                        name="BenchpCube15_BenchStingrayPBS1_0"
                        geometry={nodes.BenchpCube15_BenchStingrayPBS1_0.geometry}
                        material={materials.BenchStingrayPBS1}
                      />
                    </group>
                    <group name="BenchpCube16" position={[0, 0, -1.845]}>
                      <mesh
                        name="BenchpCube16_BenchStingrayPBS1_0"
                        geometry={nodes.BenchpCube16_BenchStingrayPBS1_0.geometry}
                        material={materials.BenchStingrayPBS1}
                      />
                    </group>
                  </group>
                </group>
                <group
                  name="Bamboo1"
                  position={[-3.713, 8.821, -0.253]}
                  rotation={[-0.111, 1.293, 0.084]}
                  scale={[0.705, 5.456, 1]}>
                  <mesh
                    name="Bamboo1_BambooStingrayPBS2_0"
                    geometry={nodes.Bamboo1_BambooStingrayPBS2_0.geometry}
                    material={materials.BambooStingrayPBS2}
                  />
                  <group
                    name="BamboopCylinder1"
                    position={[1, -0.623, 2.112]}
                    rotation={[0.547, -1.131, 0.5]}
                    scale={[0.731, 1.025, 1.334]}>
                    <mesh
                      name="BamboopCylinder1_BambooStingrayPBS2_0"
                      geometry={nodes.BamboopCylinder1_BambooStingrayPBS2_0.geometry}
                      material={materials.BambooStingrayPBS2}
                    />
                  </group>
                  <group
                    name="pCylinder1"
                    position={[-34.969, 0.249, -2.282]}
                    rotation={[0.547, -1.131, 0.5]}
                    scale={[0.731, 1.025, 1.334]}>
                    <mesh
                      name="pCylinder1_BambooStingrayPBS2_0"
                      geometry={nodes.pCylinder1_BambooStingrayPBS2_0.geometry}
                      material={materials.BambooStingrayPBS2}
                    />
                  </group>
                  <group
                    name="pCylinder2"
                    position={[-33.745, -0.248, 0.466]}
                    rotation={[1.364, -1.325, 1.278]}
                    scale={[0.731, 1.025, 1.334]}>
                    <mesh
                      name="pCylinder2_BambooStingrayPBS2_0"
                      geometry={nodes.pCylinder2_BambooStingrayPBS2_0.geometry}
                      material={materials.BambooStingrayPBS2}
                    />
                  </group>
                  <group
                    name="pCylinder3"
                    position={[-49.164, -1.504, 46.435]}
                    rotation={[1.364, -1.325, 1.278]}
                    scale={[0.731, 1.025, 1.334]}>
                    <mesh
                      name="pCylinder3_BambooStingrayPBS2_0"
                      geometry={nodes.pCylinder3_BambooStingrayPBS2_0.geometry}
                      material={materials.BambooStingrayPBS2}
                    />
                  </group>
                  <group
                    name="pCylinder4"
                    position={[-38.871, -1.945, 50.141]}
                    rotation={[0.181, -0.617, 0.209]}
                    scale={[0.416, 0.583, 0.759]}>
                    <mesh
                      name="pCylinder4_BambooStingrayPBS2_0"
                      geometry={nodes.pCylinder4_BambooStingrayPBS2_0.geometry}
                      material={materials.BambooStingrayPBS2}
                    />
                  </group>
                  <group
                    name="pCylinder5"
                    position={[42.784, -1.128, 28.08]}
                    rotation={[1.364, -1.325, 1.278]}
                    scale={[0.731, 1.025, 1.334]}>
                    <mesh
                      name="pCylinder5_BambooStingrayPBS2_0"
                      geometry={nodes.pCylinder5_BambooStingrayPBS2_0.geometry}
                      material={materials.BambooStingrayPBS2}
                    />
                  </group>
                  <group
                    name="pCylinder6"
                    position={[44.328, -1.652, 31.608]}
                    rotation={[0.3, -0.872, 0.29]}
                    scale={[0.731, 1.025, 1.334]}>
                    <mesh
                      name="pCylinder6_BambooStingrayPBS2_0"
                      geometry={nodes.pCylinder6_BambooStingrayPBS2_0.geometry}
                      material={materials.BambooStingrayPBS2}
                    />
                  </group>
                  <group
                    name="pCylinder7"
                    position={[46.567, -0.63, 28.811]}
                    rotation={[0.3, -0.872, 0.29]}
                    scale={[0.731, 1.025, 1.334]}>
                    <mesh
                      name="pCylinder7_BambooStingrayPBS2_0"
                      geometry={nodes.pCylinder7_BambooStingrayPBS2_0.geometry}
                      material={materials.BambooStingrayPBS2}
                    />
                  </group>
                  <group
                    name="pCylinder8"
                    position={[70.13, -0.534, -15.128]}
                    rotation={[0.3, -0.872, 0.29]}
                    scale={[0.731, 1.025, 1.334]}>
                    <mesh
                      name="pCylinder8_BambooStingrayPBS2_0"
                      geometry={nodes.pCylinder8_BambooStingrayPBS2_0.geometry}
                      material={materials.BambooStingrayPBS2}
                    />
                  </group>
                </group>
                <group name="Lily1">
                  <mesh
                    name="Lily1_LilyStingrayPBS1_0"
                    geometry={nodes.Lily1_LilyStingrayPBS1_0.geometry}
                    material={materials.LilyStingrayPBS1}
                  />
                  <group name="pCylinder11">
                    <mesh
                      name="pCylinder11_LilyStingrayPBS1_0"
                      geometry={nodes.pCylinder11_LilyStingrayPBS1_0.geometry}
                      material={materials.LilyStingrayPBS1}
                    />
                  </group>
                  <group name="pCylinder10">
                    <mesh
                      name="pCylinder10_LilyStingrayPBS1_0"
                      geometry={nodes.pCylinder10_LilyStingrayPBS1_0.geometry}
                      material={materials.LilyStingrayPBS1}
                    />
                  </group>
                  <group name="pCylinder9">
                    <mesh
                      name="pCylinder9_LilyStingrayPBS1_0"
                      geometry={nodes.pCylinder9_LilyStingrayPBS1_0.geometry}
                      material={materials.LilyStingrayPBS1}
                    />
                  </group>
                  <group name="pCylinder1_1">
                    <mesh
                      name="pCylinder1_LilyStingrayPBS1_0"
                      geometry={nodes.pCylinder1_LilyStingrayPBS1_0.geometry}
                      material={materials.LilyStingrayPBS1}
                    />
                  </group>
                  <group name="LilypCylinder1">
                    <mesh
                      name="LilypCylinder1_LilyStingrayPBS1_0"
                      geometry={nodes.LilypCylinder1_LilyStingrayPBS1_0.geometry}
                      material={materials.LilyStingrayPBS1}
                    />
                  </group>
                  <group name="pCylinder12">
                    <mesh
                      name="pCylinder12_LilyStingrayPBS1_0"
                      geometry={nodes.pCylinder12_LilyStingrayPBS1_0.geometry}
                      material={materials.LilyStingrayPBS1}
                    />
                  </group>
                </group>
                <group
                  name="deerscarepCube1"
                  position={[9.263, 1.162, -35.089]}
                  rotation={[-Math.PI, -0.794, -Math.PI]}
                  scale={[1.236, 1.345, 1.236]}>
                  <mesh
                    name="deerscarepCube1_deerscareStingrayPBS1_0"
                    geometry={nodes.deerscarepCube1_deerscareStingrayPBS1_0.geometry}
                    material={materials.deerscareStingrayPBS1}
                  />
                  <group
                    name="deerscarepCylinder4"
                    position={[-1.345, 6.874, 2.887]}
                    rotation={[-1.488, 0.07, 0.855]}
                    scale={[0.156, 1.122, 0.134]}>
                    <mesh
                      name="deerscarepCylinder4_deerscareStingrayPBS5_0"
                      geometry={nodes.deerscarepCylinder4_deerscareStingrayPBS5_0.geometry}
                      material={materials.deerscareStingrayPBS5}
                    />
                  </group>
                  <group
                    name="deerscarepCylinder3"
                    position={[0.574, 3.328, 2.563]}
                    rotation={[2.753, -0.684, -1.651]}
                    scale={[0.203, 1.57, 0.203]}>
                    <mesh
                      name="deerscarepCylinder3_deerscareStingrayPBS5_0"
                      geometry={nodes.deerscarepCylinder3_deerscareStingrayPBS5_0.geometry}
                      material={materials.deerscareStingrayPBS5}
                    />
                  </group>
                  <group
                    name="deerscarepCylinder2"
                    position={[-2.254, 3.778, 2.193]}
                    scale={[0.394, 3.43, 0.389]}>
                    <mesh
                      name="deerscarepCylinder2_deerscareStingrayPBS5_0"
                      geometry={nodes.deerscarepCylinder2_deerscareStingrayPBS5_0.geometry}
                      material={materials.deerscareStingrayPBS5}
                    />
                  </group>
                  <group
                    name="deerscaredeerscarepCylinder2"
                    position={[2.278, 2.209, 2.193]}
                    scale={[0.394, 2.117, 0.389]}>
                    <mesh
                      name="deerscaredeerscarepCylinder2_deerscareStingrayPBS5_0"
                      geometry={nodes.deerscaredeerscarepCylinder2_deerscareStingrayPBS5_0.geometry}
                      material={materials.deerscareStingrayPBS5}
                    />
                  </group>
                  <group
                    name="deerscaredeerscarepCylinder5"
                    position={[0, 0.528, 4.702]}
                    scale={[1.822, 0.118, 1.822]}>
                    <mesh
                      name="deerscaredeerscarepCylinder5_deerscareStingrayPBS5_0"
                      geometry={nodes.deerscaredeerscarepCylinder5_deerscareStingrayPBS5_0.geometry}
                      material={materials.deerscareStingrayPBS5}
                    />
                  </group>
                  <group
                    name="deerscarepCylinder1"
                    position={[0, 0.498, 4.625]}
                    scale={[1.802, 0.084, 1.737]}>
                    <mesh
                      name="deerscarepCylinder1_deerscarelambert2_0"
                      geometry={nodes.deerscarepCylinder1_deerscarelambert2_0.geometry}
                      material={materials.deerscarelambert2}
                    />
                  </group>
                  <group
                    name="deerscaredeerscarepCylinder4"
                    position={[0, 4.031, 2.214]}
                    rotation={[-2.409, -0.067, -0.013]}
                    scale={[0.534, 3.661, 0.481]}>
                    <mesh
                      name="deerscaredeerscarepCylinder4_deerscareStingrayPBS5_0"
                      geometry={nodes.deerscaredeerscarepCylinder4_deerscareStingrayPBS5_0.geometry}
                      material={materials.deerscareStingrayPBS5}
                    />
                  </group>
                </group>
                <group name="CattailCatTail">
                  <mesh
                    name="CattailCatTail_CattailStingrayPBS1_0"
                    geometry={nodes.CattailCatTail_CattailStingrayPBS1_0.geometry}
                    material={materials.CattailStingrayPBS1}
                  />
                  <group name="CattailpCylinder2">
                    <mesh
                      name="CattailpCylinder2_CattailStingrayPBS1_0"
                      geometry={nodes.CattailpCylinder2_CattailStingrayPBS1_0.geometry}
                      material={materials.CattailStingrayPBS1}
                    />
                  </group>
                  <group name="CattailpCylinder1">
                    <mesh
                      name="CattailpCylinder1_CattailStingrayPBS1_0"
                      geometry={nodes.CattailpCylinder1_CattailStingrayPBS1_0.geometry}
                      material={materials.CattailStingrayPBS1}
                    />
                  </group>
                  <group name="CattailpSphere2">
                    <mesh
                      name="CattailpSphere2_CattailStingrayPBS1_0"
                      geometry={nodes.CattailpSphere2_CattailStingrayPBS1_0.geometry}
                      material={materials.CattailStingrayPBS1}
                    />
                  </group>
                </group>
                <group name="CatTail">
                  <mesh
                    name="CatTail_CattailStingrayPBS1_0"
                    geometry={nodes.CatTail_CattailStingrayPBS1_0.geometry}
                    material={materials.CattailStingrayPBS1}
                  />
                  <group name="pCylinder2_1">
                    <mesh
                      name="pCylinder2_CattailStingrayPBS1_0"
                      geometry={nodes.pCylinder2_CattailStingrayPBS1_0.geometry}
                      material={materials.CattailStingrayPBS1}
                    />
                  </group>
                  <group name="pCylinder1_2">
                    <mesh
                      name="pCylinder1_CattailStingrayPBS1_0"
                      geometry={nodes.pCylinder1_CattailStingrayPBS1_0.geometry}
                      material={materials.CattailStingrayPBS1}
                    />
                  </group>
                  <group name="pSphere2">
                    <mesh
                      name="pSphere2_CattailStingrayPBS1_0"
                      geometry={nodes.pSphere2_CattailStingrayPBS1_0.geometry}
                      material={materials.CattailStingrayPBS1}
                    />
                  </group>
                </group>
                <group name="CatTail1">
                  <mesh
                    name="CatTail1_CattailStingrayPBS1_0"
                    geometry={nodes.CatTail1_CattailStingrayPBS1_0.geometry}
                    material={materials.CattailStingrayPBS1}
                  />
                  <group name="pCylinder2_2">
                    <mesh
                      name="pCylinder2_CattailStingrayPBS1_0_1"
                      geometry={nodes.pCylinder2_CattailStingrayPBS1_0_1.geometry}
                      material={materials.CattailStingrayPBS1}
                    />
                  </group>
                  <group name="pCylinder1_3">
                    <mesh
                      name="pCylinder1_CattailStingrayPBS1_0_1"
                      geometry={nodes.pCylinder1_CattailStingrayPBS1_0_1.geometry}
                      material={materials.CattailStingrayPBS1}
                    />
                  </group>
                  <group name="pSphere2_1">
                    <mesh
                      name="pSphere2_CattailStingrayPBS1_0_1"
                      geometry={nodes.pSphere2_CattailStingrayPBS1_0_1.geometry}
                      material={materials.CattailStingrayPBS1}
                    />
                  </group>
                </group>
                <group name="Tree_Petals">
                  <mesh
                    name="Tree_Petals_lambert5_0"
                    geometry={nodes.Tree_Petals_lambert5_0.geometry}
                    material={materials.lambert5}
                  />
                  <group name="pPlane16">
                    <mesh
                      name="pPlane16_lambert5_0"
                      geometry={nodes.pPlane16_lambert5_0.geometry}
                      material={materials.lambert5}
                    />
                  </group>
                  <group name="pPlane15">
                    <mesh
                      name="pPlane15_lambert5_0"
                      geometry={nodes.pPlane15_lambert5_0.geometry}
                      material={materials.lambert5}
                    />
                  </group>
                  <group name="pPlane14">
                    <mesh
                      name="pPlane14_lambert5_0"
                      geometry={nodes.pPlane14_lambert5_0.geometry}
                      material={materials.lambert5}
                    />
                  </group>
                  <group name="pPlane13">
                    <mesh
                      name="pPlane13_lambert5_0"
                      geometry={nodes.pPlane13_lambert5_0.geometry}
                      material={materials.lambert5}
                    />
                  </group>
                  <group name="pPlane12">
                    <mesh
                      name="pPlane12_lambert5_0"
                      geometry={nodes.pPlane12_lambert5_0.geometry}
                      material={materials.lambert5}
                    />
                  </group>
                  <group name="pPlane11">
                    <mesh
                      name="pPlane11_lambert5_0"
                      geometry={nodes.pPlane11_lambert5_0.geometry}
                      material={materials.lambert5}
                    />
                  </group>
                  <group name="pPlane10">
                    <mesh
                      name="pPlane10_lambert5_0"
                      geometry={nodes.pPlane10_lambert5_0.geometry}
                      material={materials.lambert5}
                    />
                  </group>
                  <group name="pPlane19">
                    <mesh
                      name="pPlane19_lambert5_0"
                      geometry={nodes.pPlane19_lambert5_0.geometry}
                      material={materials.lambert5}
                    />
                  </group>
                </group>
                <group
                  name="Lantern4"
                  position={[-6.121, 31.373, -0.022]}
                  rotation={[-3.076, 0.003, 0.052]}
                  scale={[0.601, 0.171, 0.601]}>
                  <mesh
                    name="Lantern4_Lantern2StingrayPBS1_0"
                    geometry={nodes.Lantern4_Lantern2StingrayPBS1_0.geometry}
                    material={materials.Lantern2StingrayPBS1}
                  />
                  <group name="Lantern2pSphere3" position={[-0.099, 56.421, -0.336]}>
                    <mesh
                      name="Lantern2pSphere3_Lantern2StingrayPBS1_0"
                      geometry={nodes.Lantern2pSphere3_Lantern2StingrayPBS1_0.geometry}
                      material={materials.Lantern2StingrayPBS1}
                    />
                  </group>
                  <group
                    name="Lantern2pCylinder3"
                    position={[-0.099, 52.675, -0.316]}
                    rotation={[3.136, 0, 0]}
                    scale={[0.034, 3.657, 0.034]}>
                    <mesh
                      name="Lantern2pCylinder3_Lantern2StingrayPBS1_0"
                      geometry={nodes.Lantern2pCylinder3_Lantern2StingrayPBS1_0.geometry}
                      material={materials.Lantern2StingrayPBS1}
                    />
                  </group>
                  <group name="Lantern2pCylinder2" position={[-0.099, 49.262, -0.298]}>
                    <mesh
                      name="Lantern2pCylinder2_Lantern2StingrayPBS1_0"
                      geometry={nodes.Lantern2pCylinder2_Lantern2StingrayPBS1_0.geometry}
                      material={materials.Lantern2StingrayPBS1}
                    />
                  </group>
                  <group
                    name="pointLight1"
                    position={[0.385, 35.036, 8.09]}
                    rotation={[3.136, 0, 0]}
                    scale={[2.706, 9.512, 2.707]}>
                    <group name="Object_342" rotation={[Math.PI / 2, 0, 0]}>
                      <group name="Object_343" />
                    </group>
                  </group>
                  <group
                    name="Lantern2pSphere2"
                    position={[-0.099, 39.663, -0.247]}
                    rotation={[3.136, 0, 0]}
                    scale={[2.706, 9.512, 2.707]}>
                    <mesh
                      name="Lantern2pSphere2_lambert1_0"
                      geometry={nodes.Lantern2pSphere2_lambert1_0.geometry}
                      material={materials.lambert1}
                    />
                  </group>
                  <group
                    name="pCylinder3_1"
                    position={[-0.099, 15.05, -0.117]}
                    rotation={[3.136, 0, 0]}
                    scale={[0.034, 14.89, 0.034]}>
                    <mesh
                      name="pCylinder3_Lantern2StingrayPBS1_0"
                      geometry={nodes.pCylinder3_Lantern2StingrayPBS1_0.geometry}
                      material={materials.Lantern2StingrayPBS1}
                    />
                  </group>
                </group>
                <group
                  name="bottom"
                  position={[0, -1000.1, 0]}
                  rotation={[Math.PI / 2, Math.PI / 2, 0]}>
                  <group name="Object_349" />
                </group>
                <group
                  name="Island_2"
                  position={[15.614, -2.079, -37.538]}
                  rotation={[0, -1.56, 0]}
                  scale={[29.513, 6.519, 49.35]}>
                  <mesh
                    name="Island_2_StingrayPBS2_0"
                    geometry={nodes.Island_2_StingrayPBS2_0.geometry}
                    material={materials.StingrayPBS2}
                  />
                </group>
                <group
                  name="Koi3"
                  position={[44.739, -3.489, -0.39]}
                  rotation={[0.521, 0.825, -0.311]}
                  scale={0.46}>
                  <mesh
                    name="Koi3_KoiStingrayPBS1_0"
                    geometry={nodes.Koi3_KoiStingrayPBS1_0.geometry}
                    material={materials.KoiStingrayPBS1}
                  />
                  <group
                    name="pCube2_2"
                    position={[0, 0.848, 2.21]}
                    rotation={[2.991, 0, 0]}
                    scale={[0.154, 1, 1]}>
                    <mesh
                      name="pCube2_KoiStingrayPBS1_0_2"
                      geometry={nodes.pCube2_KoiStingrayPBS1_0_2.geometry}
                      material={materials.KoiStingrayPBS1}
                    />
                  </group>
                  <group name="pCube1_3" position={[0, 3.649, 0]} scale={[0.154, 1, 1]}>
                    <mesh
                      name="pCube1_KoiStingrayPBS1_0_2"
                      geometry={nodes.pCube1_KoiStingrayPBS1_0_2.geometry}
                      material={materials.KoiStingrayPBS1}
                    />
                  </group>
                  <group
                    name="Fin1_2"
                    position={[1.276, 1.338, -2.335]}
                    rotation={[0, 0.699, 0]}
                    scale={[0.109, 0.817, 0.817]}>
                    <mesh
                      name="Fin1_KoiStingrayPBS1_0_2"
                      geometry={nodes.Fin1_KoiStingrayPBS1_0_2.geometry}
                      material={materials.KoiStingrayPBS1}
                    />
                  </group>
                  <group
                    name="Fin_2"
                    position={[-1.421, 1.33, -2.335]}
                    rotation={[0, -0.676, 0]}
                    scale={[0.109, 0.817, 0.817]}>
                    <mesh
                      name="Fin_KoiStingrayPBS1_0_2"
                      geometry={nodes.Fin_KoiStingrayPBS1_0_2.geometry}
                      material={materials.KoiStingrayPBS1}
                    />
                  </group>
                </group>
                <group name="CatTail2">
                  <mesh
                    name="CatTail2_CattailStingrayPBS1_0"
                    geometry={nodes.CatTail2_CattailStingrayPBS1_0.geometry}
                    material={materials.CattailStingrayPBS1}
                  />
                  <group name="pCylinder2_3">
                    <mesh
                      name="pCylinder2_CattailStingrayPBS1_0_2"
                      geometry={nodes.pCylinder2_CattailStingrayPBS1_0_2.geometry}
                      material={materials.CattailStingrayPBS1}
                    />
                  </group>
                  <group name="pCylinder1_4">
                    <mesh
                      name="pCylinder1_CattailStingrayPBS1_0_2"
                      geometry={nodes.pCylinder1_CattailStingrayPBS1_0_2.geometry}
                      material={materials.CattailStingrayPBS1}
                    />
                  </group>
                  <group name="pSphere2_2">
                    <mesh
                      name="pSphere2_CattailStingrayPBS1_0_2"
                      geometry={nodes.pSphere2_CattailStingrayPBS1_0_2.geometry}
                      material={materials.CattailStingrayPBS1}
                    />
                  </group>
                </group>
                <group name="Koi4" position={[14.913, 0, 53.891]}>
                  <mesh
                    name="Koi4_KoiStingrayPBS1_0"
                    geometry={nodes.Koi4_KoiStingrayPBS1_0.geometry}
                    material={materials.KoiStingrayPBS1}
                  />
                  <group name="pCube2_3">
                    <mesh
                      name="pCube2_KoiStingrayPBS1_0_3"
                      geometry={nodes.pCube2_KoiStingrayPBS1_0_3.geometry}
                      material={materials.KoiStingrayPBS1}
                    />
                  </group>
                  <group name="pCube1_4">
                    <mesh
                      name="pCube1_KoiStingrayPBS1_0_3"
                      geometry={nodes.pCube1_KoiStingrayPBS1_0_3.geometry}
                      material={materials.KoiStingrayPBS1}
                    />
                  </group>
                  <group name="Fin1_3">
                    <mesh
                      name="Fin1_KoiStingrayPBS1_0_3"
                      geometry={nodes.Fin1_KoiStingrayPBS1_0_3.geometry}
                      material={materials.KoiStingrayPBS1}
                    />
                  </group>
                  <group name="Fin_3">
                    <mesh
                      name="Fin_KoiStingrayPBS1_0_3"
                      geometry={nodes.Fin_KoiStingrayPBS1_0_3.geometry}
                      material={materials.KoiStingrayPBS1}
                    />
                  </group>
                </group>
                <group
                  name="Koi5"
                  position={[44.739, -7.077, 87.67]}
                  rotation={[0.521, 0.825, -0.311]}
                  scale={0.735}>
                  <mesh
                    name="Koi5_KoiStingrayPBS1_0"
                    geometry={nodes.Koi5_KoiStingrayPBS1_0.geometry}
                    material={materials.KoiStingrayPBS1}
                  />
                  <group
                    name="pCube2_4"
                    position={[0, 0.848, 2.21]}
                    rotation={[2.991, 0, 0]}
                    scale={[0.154, 1, 1]}>
                    <mesh
                      name="pCube2_KoiStingrayPBS1_0_4"
                      geometry={nodes.pCube2_KoiStingrayPBS1_0_4.geometry}
                      material={materials.KoiStingrayPBS1}
                    />
                  </group>
                  <group name="pCube1_5" position={[0, 3.649, 0]} scale={[0.154, 1, 1]}>
                    <mesh
                      name="pCube1_KoiStingrayPBS1_0_4"
                      geometry={nodes.pCube1_KoiStingrayPBS1_0_4.geometry}
                      material={materials.KoiStingrayPBS1}
                    />
                  </group>
                  <group
                    name="Fin1_4"
                    position={[1.276, 1.338, -2.335]}
                    rotation={[0, 0.699, 0]}
                    scale={[0.109, 0.817, 0.817]}>
                    <mesh
                      name="Fin1_KoiStingrayPBS1_0_4"
                      geometry={nodes.Fin1_KoiStingrayPBS1_0_4.geometry}
                      material={materials.KoiStingrayPBS1}
                    />
                  </group>
                  <group
                    name="Fin_4"
                    position={[-1.421, 1.33, -2.335]}
                    rotation={[0, -0.676, 0]}
                    scale={[0.109, 0.817, 0.817]}>
                    <mesh
                      name="Fin_KoiStingrayPBS1_0_4"
                      geometry={nodes.Fin_KoiStingrayPBS1_0_4.geometry}
                      material={materials.KoiStingrayPBS1}
                    />
                  </group>
                </group>
                <group
                  name="Lantern5"
                  position={[-16.751, 35.689, 19.891]}
                  rotation={[-0.02, 0.096, -3.027]}
                  scale={[0.601, 0.171, 0.601]}>
                  <mesh
                    name="Lantern5_Lantern2StingrayPBS1_0"
                    geometry={nodes.Lantern5_Lantern2StingrayPBS1_0.geometry}
                    material={materials.Lantern2StingrayPBS1}
                  />
                  <group name="pSphere3" position={[0.233, 46.441, -0.186]}>
                    <mesh
                      name="pSphere3_Lantern2StingrayPBS1_0"
                      geometry={nodes.pSphere3_Lantern2StingrayPBS1_0.geometry}
                      material={materials.Lantern2StingrayPBS1}
                    />
                  </group>
                  <group
                    name="pCylinder3_2"
                    position={[0.233, 42.694, -0.167]}
                    rotation={[3.136, 0, 0]}
                    scale={[0.034, 3.657, 0.034]}>
                    <mesh
                      name="pCylinder3_Lantern2StingrayPBS1_0_1"
                      geometry={nodes.pCylinder3_Lantern2StingrayPBS1_0_1.geometry}
                      material={materials.Lantern2StingrayPBS1}
                    />
                  </group>
                  <group name="pCylinder2_4" position={[0.233, 39.282, -0.149]}>
                    <mesh
                      name="pCylinder2_Lantern2StingrayPBS1_0"
                      geometry={nodes.pCylinder2_Lantern2StingrayPBS1_0.geometry}
                      material={materials.Lantern2StingrayPBS1}
                    />
                  </group>
                  <group
                    name="pSphere2_3"
                    position={[-0.08, 2.868, -0.036]}
                    rotation={[3.136, 0, 0]}
                    scale={[2.706, 9.512, 2.707]}>
                    <mesh
                      name="pSphere2_lambert1_0"
                      geometry={nodes.pSphere2_lambert1_0.geometry}
                      material={materials.lambert1}
                    />
                  </group>
                  <group
                    name="pCylinder13"
                    position={[0.246, 12.406, -0.034]}
                    rotation={[3.136, 0, 0]}
                    scale={[0.034, 7.382, 0.034]}>
                    <mesh
                      name="pCylinder13_Lantern2StingrayPBS1_0"
                      geometry={nodes.pCylinder13_Lantern2StingrayPBS1_0.geometry}
                      material={materials.Lantern2StingrayPBS1}
                    />
                  </group>
                </group>
                <group
                  name="Lantern3"
                  position={[-6.212, 33.39, -9.223]}
                  rotation={[0.027, 0.096, 3.117]}
                  scale={[0.601, 0.171, 0.601]}>
                  <mesh
                    name="Lantern3_Lantern2StingrayPBS1_0"
                    geometry={nodes.Lantern3_Lantern2StingrayPBS1_0.geometry}
                    material={materials.Lantern2StingrayPBS1}
                  />
                  <group name="pSphere3_1" position={[-0.035, 39.091, 0.03]}>
                    <mesh
                      name="pSphere3_Lantern2StingrayPBS1_0_1"
                      geometry={nodes.pSphere3_Lantern2StingrayPBS1_0_1.geometry}
                      material={materials.Lantern2StingrayPBS1}
                    />
                  </group>
                  <group
                    name="pCylinder3_3"
                    position={[-0.035, 35.344, 0.05]}
                    rotation={[3.136, 0, 0]}
                    scale={[0.034, 3.657, 0.034]}>
                    <mesh
                      name="pCylinder3_Lantern2StingrayPBS1_0_2"
                      geometry={nodes.pCylinder3_Lantern2StingrayPBS1_0_2.geometry}
                      material={materials.Lantern2StingrayPBS1}
                    />
                  </group>
                  <group name="pCylinder2_5" position={[-0.035, 31.932, 0.068]}>
                    <mesh
                      name="pCylinder2_Lantern2StingrayPBS1_0_1"
                      geometry={nodes.pCylinder2_Lantern2StingrayPBS1_0_1.geometry}
                      material={materials.Lantern2StingrayPBS1}
                    />
                  </group>
                  <group
                    name="pSphere2_4"
                    position={[-0.035, 22.332, 0.119]}
                    rotation={[3.136, 0, 0]}
                    scale={[2.706, 9.512, 2.707]}>
                    <mesh
                      name="pSphere2_lambert1_0_1"
                      geometry={nodes.pSphere2_lambert1_0_1.geometry}
                      material={materials.lambert1}
                    />
                  </group>
                  <group
                    name="pCylinder13_1"
                    position={[-0.022, 5.055, 0.183]}
                    rotation={[3.136, 0, 0]}
                    scale={[0.034, 7.382, 0.034]}>
                    <mesh
                      name="pCylinder13_Lantern2StingrayPBS1_0_1"
                      geometry={nodes.pCylinder13_Lantern2StingrayPBS1_0_1.geometry}
                      material={materials.Lantern2StingrayPBS1}
                    />
                  </group>
                  <group
                    name="pointLight2"
                    position={[-10.998, 30.438, 47.558]}
                    rotation={[0.005, 0.096, 3.141]}
                    scale={[2.706, 9.512, 2.707]}>
                    <group name="Object_415" rotation={[Math.PI / 2, 0, 0]}>
                      <group name="Object_416" />
                    </group>
                  </group>
                </group>
                <group
                  name="Lantern6"
                  position={[3.053, 35.122, 18.389]}
                  rotation={[0.043, 0.095, 3.07]}
                  scale={[0.601, 0.171, 0.601]}>
                  <mesh
                    name="Lantern6_Lantern2StingrayPBS1_0"
                    geometry={nodes.Lantern6_Lantern2StingrayPBS1_0.geometry}
                    material={materials.Lantern2StingrayPBS1}
                  />
                  <group name="pSphere3_2" position={[0.177, 41.635, -0.175]}>
                    <mesh
                      name="pSphere3_Lantern2StingrayPBS1_0_2"
                      geometry={nodes.pSphere3_Lantern2StingrayPBS1_0_2.geometry}
                      material={materials.Lantern2StingrayPBS1}
                    />
                  </group>
                  <group
                    name="pCylinder3_4"
                    position={[0.177, 37.889, -0.156]}
                    rotation={[3.136, 0, 0]}
                    scale={[0.034, 3.657, 0.034]}>
                    <mesh
                      name="pCylinder3_Lantern2StingrayPBS1_0_3"
                      geometry={nodes.pCylinder3_Lantern2StingrayPBS1_0_3.geometry}
                      material={materials.Lantern2StingrayPBS1}
                    />
                  </group>
                  <group name="pCylinder2_6" position={[0.177, 34.477, -0.137]}>
                    <mesh
                      name="pCylinder2_Lantern2StingrayPBS1_0_2"
                      geometry={nodes.pCylinder2_Lantern2StingrayPBS1_0_2.geometry}
                      material={materials.Lantern2StingrayPBS1}
                    />
                  </group>
                  <group
                    name="pSphere2_5"
                    position={[0.177, 24.877, -0.087]}
                    rotation={[3.136, 0, 0]}
                    scale={[2.706, 9.512, 2.707]}>
                    <mesh
                      name="pSphere2_lambert1_0_2"
                      geometry={nodes.pSphere2_lambert1_0_2.geometry}
                      material={materials.lambert1}
                    />
                  </group>
                  <group
                    name="pCylinder13_2"
                    position={[0.19, 7.6, -0.023]}
                    rotation={[3.136, 0, 0]}
                    scale={[0.034, 7.382, 0.034]}>
                    <mesh
                      name="pCylinder13_Lantern2StingrayPBS1_0_2"
                      geometry={nodes.pCylinder13_Lantern2StingrayPBS1_0_2.geometry}
                      material={materials.Lantern2StingrayPBS1}
                    />
                  </group>
                  <group
                    name="pointLight3"
                    position={[36.547, 47.31, -1.186]}
                    rotation={[0.005, 0.096, 3.141]}
                    scale={[2.706, 9.512, 2.707]}>
                    <group name="Object_430" rotation={[Math.PI / 2, 0, 0]}>
                      <group name="Object_431" />
                    </group>
                  </group>
                </group>
                <group
                  name="pPlane20"
                  position={[12.145, -11.218, -0.166]}
                  scale={[483.865, 485.21, 483.865]}>
                  <mesh
                    name="pPlane20_lambert4_0"
                    geometry={nodes.pPlane20_lambert4_0.geometry}
                    material={materials.lambert4}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </a.group>
  )
}
