/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Paul (https://sketchfab.com/paul_paul_paul)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/free-skybox-in-the-cloud-b270497defe24f9cb497b9a075eeb28f
Title: FREE - SkyBox In The Cloud
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export function Sky({ isRotating, ...props }) {
  const { nodes, materials } = useGLTF('/3d/sky.glb')
  const skyRef = useRef()
  useFrame(({ clock }) => {
    if (isRotating) {
      skyRef.current.rotation.y += 0.0003
    }
  })
  return (
    <group ref={skyRef} {...props} dispose={null}>
      <group scale={0.01}>
        <mesh
          geometry={nodes.Sphere__0.geometry}
          material={materials['Scene_-_Root']}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={50000}
        />
      </group>
    </group>
  )
}
