/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Hannes Delbeke (https://sketchfab.com/han)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/fantasy-sky-background-15c79bb2fc1147128039fe4ff90fd5a0
Title: Fantasy Sky Background
*/

import React, { useRef } from 'react'
import { useGLTF, useTexture } from '@react-three/drei'

export function SkyBackground({ isRotating, ...props }) {
  const { nodes, materials } = useGLTF('/3d/fantasy_sky_background-1.glb')
  const t = useTexture()
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={1.548}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object001_Material__25__background_JPG_002_0.geometry}
          material={materials.Material__25__background_JPG_002}
          rotation={[Math.PI / 2, 0, 0]}
        >
        </mesh>
      </group>
    </group>
  )
}