/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Agustín Hönnun (https://sketchfab.com/Agustin_Honnun)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/stylized-spawn-point-f3a76618b8434ceeb5398478b87639a3
Title: Stylized Spawn point
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame, useThree } from '@react-three/fiber'
import { a } from '@react-spring/three';
// import TreeScene from '@/assets/3d/island.glb';

const Tree = (props) => {
  const { nodes, materials } = useGLTF('/3d/tree.glb')
  const treeRef = useRef();
  return (
    <a.group ref={treeRef} {...props}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={3.387}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0.06, 0.11, -0.208]}>
            <mesh
              geometry={nodes.Object_10.geometry}
              material={materials.Foliage_MAT}
            />
            <mesh
              geometry={nodes.Object_11.geometry}
              material={materials.Water_MAT}
            />
          </group>
          <group position={[-0.794, 1.191, 0.152]}>
            <mesh
              geometry={nodes.Object_32.geometry}
              material={materials.TreeLeaves_MAT}
            />
            <mesh
              geometry={nodes.Object_33.geometry}
              material={materials.Foliage_MAT}
            />
          </group>
          <mesh
            geometry={nodes.Object_4.geometry}
            material={materials.Lights_MAT}
            position={[0.464, 0.85, 0.364]}
          />
          <mesh
            geometry={nodes.Object_6.geometry}
            material={materials.Foliage_MAT}
            position={[1.031, 0.147, 0.182]}
            rotation={[0.267, -0.247, -0.136]}
            scale={0.288}
          />
          <mesh
            geometry={nodes.Object_8.geometry}
            material={materials.Grass_MAT}
          />
          <mesh
            geometry={nodes.Object_13.geometry}
            material={materials.Base_Base_MAT}
            position={[0, 0.079, 0]}
          />
          <mesh
            geometry={nodes.Object_15.geometry}
            material={materials.Base_Base_MAT}
            position={[0, 0.079, 0]}
          />
          <mesh
            geometry={nodes.Object_17.geometry}
            material={materials.Base_SideRocks_MAT}
          />
          <mesh
            geometry={nodes.Object_19.geometry}
            material={materials.Base_SideRocks_MAT}
          />
          <mesh
            geometry={nodes.Object_21.geometry}
            material={materials.Base_SideRocks_MAT}
          />
          <mesh
            geometry={nodes.Object_23.geometry}
            material={materials.Base_TreeBark_MAT}
          />
          <mesh
            geometry={nodes.Object_24.geometry}
            material={materials.Foliage_MAT}
          />
          <mesh
            geometry={nodes.Object_26.geometry}
            material={materials.Base_TreeBark_MAT}
          />
          <mesh
            geometry={nodes.Object_28.geometry}
            material={materials.Base_TreeBark_MAT}
          />
          <mesh
            geometry={nodes.Object_30.geometry}
            material={materials.TreeLeaves_MAT}
            position={[0.885, 1.329, 0.071]}
          />
          <mesh
            geometry={nodes.Object_35.geometry}
            material={materials.TreeLeaves_MAT}
            position={[0.1, 1.113, -0.608]}
            rotation={[-2.721, -0.552, -3.028]}
          />
        </group>
      </group>
    </a.group>
  )
}

export default Tree;