/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Wren MB (https://sketchfab.com/Wormsnacks)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/floaty-vase-bb2ca26fc6d6450a8e764ea14c65a52e
Title: Floaty Vase
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Vase(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/3d/floaty_vase.glb')
  const { actions } = useAnimations(animations, group)
  // useEffect(() => {
  //   actions['Take 001'].play()
  //   return () => {
  //     actions['Take 001'].stop()
  //   }
  // }, [])
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Capsule_16_0" rotation={[Math.PI / 2, 0, 0]} scale={0}>
                <mesh
                  name="Object_4"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_4.geometry}
                  material={materials.PlantRoots}
                />
              </group>
              <group name="Torus_Five_1">
                <mesh
                  name="Object_6"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_6.geometry}
                  material={materials.PlantRoots}
                />
              </group>
              <group name="Torus_Four_1_2">
                <mesh
                  name="Object_8"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_8.geometry}
                  material={materials.PlantRoots}
                />
              </group>
              <group name="Torus_One_3" scale={6.881}>
                <mesh
                  name="Object_10"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_10.geometry}
                  material={materials.PlantRoots}
                />
              </group>
              <group name="Torus_One_1_4" position={[0, -0.244, 0]}>
                <mesh
                  name="Object_12"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_12.geometry}
                  material={materials.PlantRoots}
                />
              </group>
              <group name="Torus_Three_5">
                <mesh
                  name="Object_14"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_14.geometry}
                  material={materials.PlantRoots}
                />
              </group>
              <group name="Torus_Three_1_6">
                <mesh
                  name="Object_16"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_16.geometry}
                  material={materials.PlantRoots}
                />
              </group>
              <group name="Torus_Two_1_7">
                <mesh
                  name="Object_18"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_18.geometry}
                  material={materials.PlantRoots}
                />
              </group>
              <group name="Vase_Base_8" position={[0, 0.001, 0]} scale={[0.297, 0.236, 0.297]}>
                <mesh
                  name="Object_20"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_20.geometry}
                  material={materials.PlantRoots}
                />
              </group>
              <group name="Vase_Base002_9" position={[0, 0.001, 0]} scale={[0.297, 0.236, 0.297]}>
                <mesh
                  name="Object_22"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_22.geometry}
                  material={materials.PlantRoots}
                />
              </group>
              <group
                name="Leaf_10"
                position={[0.128, 0.35, -0.164]}
                rotation={[0.334, 0, 0]}
                scale={0}>
                <mesh
                  name="Object_24"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_24.geometry}
                  material={materials.PlantRoots}
                />
              </group>
              <group name="Tinkle_Pyramid_12" rotation={[Math.PI / 2, 0, 0]} scale={0}>
                <mesh
                  name="Object_26"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_26.geometry}
                  material={materials.PlantRoots}
                />
                <group name="Tinkle_Pyramid_Ouline_11">
                  <mesh
                    name="Object_28"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_28.geometry}
                    material={materials.PlantRoots}
                  />
                </group>
              </group>
              <group name="Tinkle_Sphere_14" rotation={[Math.PI / 2, 0, 0]} scale={0}>
                <mesh
                  name="Object_30"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_30.geometry}
                  material={materials.PlantRoots}
                />
                <group name="Tinkle_Sphere_Outline_13">
                  <mesh
                    name="Object_32"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_32.geometry}
                    material={materials.PlantRoots}
                  />
                </group>
              </group>
              <group name="Tinkle_Sphere_1_16" rotation={[Math.PI / 2, 0, 0]} scale={0}>
                <mesh
                  name="Object_34"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_34.geometry}
                  material={materials.PlantRoots}
                />
                <group name="Tinkle_Sphere_Outline_1_15">
                  <mesh
                    name="Object_36"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_36.geometry}
                    material={materials.PlantRoots}
                  />
                </group>
              </group>
              <group name="Tinkle_Sphere_2_18" rotation={[Math.PI / 2, 0, 0]} scale={0}>
                <mesh
                  name="Object_38"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_38.geometry}
                  material={materials.PlantRoots}
                />
                <group name="Tinkle_Sphere_Outline_5_17">
                  <mesh
                    name="Object_40"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_40.geometry}
                    material={materials.PlantRoots}
                  />
                </group>
              </group>
              <group name="Tinkle_Sphere_Big_20" rotation={[Math.PI / 2, 0, 0]} scale={0}>
                <mesh
                  name="Object_42"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_42.geometry}
                  material={materials.PlantRoots}
                />
                <group name="Tinkle_Sphere_Outline_4_19">
                  <mesh
                    name="Object_44"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_44.geometry}
                    material={materials.PlantRoots}
                  />
                </group>
              </group>
              <group name="Tinkle_Sphere_Three_22" rotation={[Math.PI / 2, 0, 0]} scale={0}>
                <mesh
                  name="Object_46"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_46.geometry}
                  material={materials.PlantRoots}
                />
                <group name="Tinkle_Sphere_Outline_2_21">
                  <mesh
                    name="Object_48"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_48.geometry}
                    material={materials.PlantRoots}
                  />
                </group>
              </group>
              <group name="Tinkle_Sphere_Two_24" rotation={[Math.PI / 2, 0, 0]} scale={0}>
                <mesh
                  name="Object_50"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_50.geometry}
                  material={materials.PlantRoots}
                />
                <group name="Tinkle_Sphere_Outline_3_23">
                  <mesh
                    name="Object_52"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_52.geometry}
                    material={materials.PlantRoots}
                  />
                </group>
              </group>
              <group name="Tinkle_Star_26" rotation={[Math.PI / 2, 0, 0]} scale={0}>
                <mesh
                  name="Object_54"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_54.geometry}
                  material={materials.PlantRoots}
                />
                <group name="Tinkle_Star_Outline_25">
                  <mesh
                    name="Object_56"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_56.geometry}
                    material={materials.PlantRoots}
                  />
                </group>
              </group>
              <group name="Tinkle_Star_1_28" rotation={[Math.PI / 2, 0, 0]} scale={0}>
                <mesh
                  name="Object_58"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_58.geometry}
                  material={materials.PlantRoots}
                />
                <group name="Tinkle_Star_Outline_1_27">
                  <mesh
                    name="Object_60"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_60.geometry}
                    material={materials.PlantRoots}
                  />
                </group>
              </group>
              <group
                name="Root_29"
                position={[0, -0.004, 0]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={0}>
                <mesh
                  name="Object_62"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_62.geometry}
                  material={materials.PlantRoots}
                />
              </group>
              <group name="Root_1_30" rotation={[Math.PI / 2, 0, 0]} scale={0}>
                <mesh
                  name="Object_64"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_64.geometry}
                  material={materials.PlantRoots}
                />
              </group>
              <group name="Root_1_Outlines_31" rotation={[Math.PI / 2, 0, 0]} scale={0}>
                <mesh
                  name="Object_66"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_66.geometry}
                  material={materials.PlantRoots}
                />
              </group>
              <group name="Root_2_32" rotation={[Math.PI / 2, 0, 0]} scale={0}>
                <mesh
                  name="Object_68"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_68.geometry}
                  material={materials.PlantRoots}
                />
              </group>
              <group name="Root_2_Outlines_33" rotation={[Math.PI / 2, 0, 0]} scale={0}>
                <mesh
                  name="Object_70"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_70.geometry}
                  material={materials.PlantRoots}
                />
              </group>
              <group name="Root_Outlines_34" rotation={[Math.PI / 2, 0, 0]} scale={0}>
                <mesh
                  name="Object_72"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_72.geometry}
                  material={materials.PlantRoots}
                />
              </group>
              <group name="Vase_Base003_36" position={[0, 0.003, 0]} scale={[0.287, 0.228, 0.287]}>
                <mesh
                  name="Object_74"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_74.geometry}
                  material={materials.PlantRoots}
                />
                <group name="Vase_Base004_35">
                  <mesh
                    name="Object_76"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_76.geometry}
                    material={materials.PlantRoots}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}